version: '2'

services:

  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:80
    environment:
      - ASPNETCORE_ENVIRONMENT: "Docker"

  auth:
    depends_on:
      - gateway
      - db
    build:
      context: ../game-nation-auth-service/.
      dockerfile: Dockerfile
    expose:
      - 5001
    environment:
      - ASPNETCORE_ENVIRONMENT: "Docker"

  client:
    depends_on:
      - gateway
      - db
      - auth
    build:
      context: ../game-nation-client-service/.
      dockerfile: Dockerfile
    expose:
      - 5002
    environment:
      - ASPNETCORE_ENVIRONMENT: "Docker"
        
  admin:
    depends_on:
      - gateway
      - db
      - auth
    build:
      context: ../game-nation-admin-service/.
      dockerfile: Dockerfile
    expose:
      - 5003
    environment:
      - ASPNETCORE_ENVIRONMENT: "Docker"

  db:
    image: mongo
    restart: always
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
    expose:
      - 27017